title: Distortion-aware Domain Adaptation Benchmarks
description: Distortion-aware Domain Adaptation for Unsupervised Semantic Segmentation
url: https://sait-fdd.github.io/
google_site_verification: _nVdOKyv00hCnRzQvi5IDn47T7MspWyhkC0MTBzflVI
